# Generated by Django 5.2.7 on 2025-11-12 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_payment_project_task_team_teammember_worker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('foundation', 'Foundation Work'), ('framing', 'Framing & Structure'), ('finishing', 'Finishing & Details'), ('wiring', 'Wiring & Installation'), ('plumbing', 'Plumbing Work'), ('painting', 'Painting & Decorating'), ('tile_work', 'Tile Work'), ('carpentry', 'Carpentry'), ('welding', 'Welding'), ('roofing', 'Roofing')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='completed_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='worker',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'On Project'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
